// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMfqXeUZarviah18nOgVhh5KBD3rAQBY',
    appId: '1:936394850280:web:5806dee908cd82d57a2e5d',
    messagingSenderId: '936394850280',
    projectId: 'mynotes-takhi',
    authDomain: 'mynotes-takhi.firebaseapp.com',
    storageBucket: 'mynotes-takhi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQzbiaR63S5wX3FTUWUEKVhjYur-O5Dic',
    appId: '1:936394850280:android:af835f02cc2d9d4c7a2e5d',
    messagingSenderId: '936394850280',
    projectId: 'mynotes-takhi',
    storageBucket: 'mynotes-takhi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdvfu4fbEnoOaLadjFpjm2Ns5WdCwnbpo',
    appId: '1:936394850280:ios:b6fbd0c686914f307a2e5d',
    messagingSenderId: '936394850280',
    projectId: 'mynotes-takhi',
    storageBucket: 'mynotes-takhi.appspot.com',
    iosBundleId: 'ca.takhi.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdvfu4fbEnoOaLadjFpjm2Ns5WdCwnbpo',
    appId: '1:936394850280:ios:58fe2d575e84f4d37a2e5d',
    messagingSenderId: '936394850280',
    projectId: 'mynotes-takhi',
    storageBucket: 'mynotes-takhi.appspot.com',
    iosBundleId: 'ca.takhi.mynotes.RunnerTests',
  );
}
